#!/bin/bash

expname=$1
wallcondition=${2-soft}

port=~/Dropbox/Uni/Data/$wallcondition/$expname
target=out/$wallcondition/$expname/

if [ ! -d $target ]; then
	mkdir $target
	mkdir $target/medium
	mkdir $target/hard
	echo "created folder $expname"
fi

cp -u -r $port/* $target
echo "everything copied"
