#!/bin/bash
#script to push an experiment to the dropbox

expname=$1
data=${2-"n"}
wallcondition=${3-soft}

port=~/Dropbox/Uni/Data/$wallcondition/$expname


if [ ! -d $port ]; then
	mkdir $port
	mkdir $port/medium
	mkdir $port/hard
	echo "created folder $expname"
fi

nOfExps= ls -1 ../out/$wallcondition/$expname/ | wc -l
echo "$nOfExps experiments found..."

cp -u -r out/$wallcondition/$expname/* ~/Dropbox/Uni/Data/$wallcondition/$expname/ 
echo "Done"
