#!/bin/bash

expname=$1
wallcondition=${2-soft}
data=${3-"n"}

port=~/Dropbox/Uni/Data/$wallcondition/$expname
target=../out/$wallcondition/$expname/

if [ ! -d $target ]; then
	mkdir $target
	echo "created folder $expname"
fi

if [ $data = "y" ]; then
	cp $port/* $target
	echo "everyting copied"
else
	cp $port/*{Archive,Solver}* $target
	echo "Archives and Solvers copied"
fi
