#!/bin/bash
#script to push an experiment to the dropbox

expname=$1
data=${2-"n"}
wallcondition=${3-soft}

port=~/Dropbox/Uni/Data/$wallcondition/$expname


if [ ! -d $port ]; then
	mkdir $port
	echo "created folder $expname"
fi

nOfExps= ls -1 ../out/$wallcondition/$expname/ | wc -l
echo "$nOfExps experiments found..."

if [ $data = "y" ]; then
	cp -i ../out/$wallcondition/$expname/* ~/Dropbox/Uni/Data/$wallcondition/$expname/
	echo "everyting copied"
else
	cp -i ../out/$wallcondition/$expname/*{Archive,Solver}* ~/Dropbox/Uni/Data/$wallcondition/$expname/ 
	echo "Archives and Solvers copied"
fi
