#!/bin/bash
#script to push an experiment to the dropbox

expname=$1
wallcondition=${2-soft}
data=${3-"n"}

if [ $data = "y" ]; then
	cp ../out/$wallcondition/$expname/* ~/Dropbox/Uni/Data/$wallcondition/$expname/
	echo "everyting copied"
else
	cp ../out/$wallcondition/$expname/*{Archive,Solver}* ~/Dropbox/Uni/Data/$wallcondition/$expname/ 
	echo "Archives and Solvers copied"
fi
